import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");

const packagePath = path.join(root, "package.json");
const manifestPath = path.join(root, "manifest.json");
const versionPath = path.join(root, "src", "version.ts");

const readJSON = (filePath) => JSON.parse(fs.readFileSync(filePath, "utf8"));
const writeJSON = (filePath, value) => {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`);
};

const packageJSON = readJSON(packagePath);
const manifest = readJSON(manifestPath);
const version = packageJSON.version;

if (!version) {
  throw new Error("package.json is missing version");
}

if (manifest.version !== version) {
  manifest.version = version;
  writeJSON(manifestPath, manifest);
}

const versionSource = `// This file is auto-generated by scripts/sync-version.mjs
// Do not edit manually - update version in package.json instead
export const VERSION = "${version}";
`;

if (
  !fs.existsSync(versionPath) ||
  fs.readFileSync(versionPath, "utf8") !== versionSource
) {
  fs.writeFileSync(versionPath, versionSource);
}
